#
# Module manifest for module 'STIGLib'
#
# Generated by: Joseph Warren
#
# Generated on: 4/4/2020
#

@{
    RootModule           = 'STIGLib.psm1'
    ModuleVersion        = '0.1.1'
    GUID                 = 'bdf751b3-4e95-4384-b847-8696bc1b7d5a'
    Author               = 'Joseph Warren'
    CompanyName          = 'No'
    Copyright            = '(c) Joseph Warren. All rights reserved.'
    Description          = 'Download STIG benchmark files'
    FunctionsToExport    = @('Get-StigFile', 'Save-StigFile')
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{
        PSData = @{
            Tags       = @('STIG', 'download')
            LicenseUri = 'https://github.com/luzkenin/STIGLib/blob/master/LICENSE.txt'
            ProjectUri = 'https://github.com/luzkenin/STIGLib'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}


